version: '3.8'

services:
    mysql:
        image: mysql:8.0.26
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: first_db
            MYSQL_USER: first_user
            MYSQL_PASSWORD: first_pass
        command:
            mysqld --default-authentication-plugin=mysql_native_password
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
